name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t repo-dev .
      - name: Run setup script
        run: |
          docker run --name repo repo-dev ./codex/setup.sh | tee test.log
      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-log
          path: test.log
